export type ThrowingPdfSection = {
  id: string;
  title: string;
  image?: string;
  paragraphs: string[];
};

export const throwingPdfReport = {
  cover: {
    title: "Motion Capture Throwing Analysis",
    tagline: "Assess, Identify, & Let's Get After It",
    website: "www.sequencebiolab.com",
  },
  metadata: [
    { label: "Name", value: "Gavin Lux" },
    { label: "Location", value: "Sequence" },
    { label: "Date", value: "" },
  ],
  findings: {
    title: "Thrower Sequence",
    paragraphs: [
      "The kinematic sequence is one of the most important determinants of efficient throwing mechanics. In elite throwers, movement is initiated from the ground up, beginning with pelvic rotation, followed by trunk rotation, elbow extension, and finally shoulder internal rotation. This proximal-to-distal sequence allows energy generated by the lower half to be transferred efficiently through the kinetic chain and ultimately expressed at ball release.",
      "A critical component of this process is the stretch-shortening cycle created between the pelvis and torso. The core musculature serves as the primary link between the lower and upper body, with attachments on both the pelvis and rib cage. This relationship allows the core to function as both a force transmitter and a mechanism for segmental separation, enabling rotational energy to be stored and released efficiently throughout the throwing motion.",
      "During his motion capture assessment, Gavin was unable to consistently achieve an optimal kinematic sequence. Specifically, peak trunk rotational velocity occurred before peak pelvic rotational velocity, disrupting the normal flow of energy through the kinetic chain. This sequencing pattern may be influenced by his limited degree of pelvic rotation at foot plant, which reduces the foundation necessary for efficient separation and rotational timing.",
      "As a result, Gavin appears to compensate by rotating the trunk prematurely and extending the elbow earlier during the period of maximal shoulder external rotation. These compensatory patterns may reduce the efficiency of force transfer and place greater demands on the upper extremity to generate velocity.",
      "Additionally, Gavin primarily creates shoulder-to-hip separation by rotating the torso over a relatively fixed pelvis rather than rotating the pelvis underneath a stable torso. While this strategy allows him to create measurable separation, it differs from the movement pattern commonly observed in elite throwers, where separation is created through pelvic rotation occurring underneath a relatively fixed trunk. This approach often allows athletes to access greater degrees of lead-leg closed-chain hip internal rotation and establish more favorable positions for force transfer later in the delivery.",
      "In Gavin's case, these timing and sequencing inefficiencies may contribute to variability in release point and reduce the consistency with which energy is transferred from the lower half into the throwing arm. Improving pelvic rotation at landing and enhancing his ability to create separation from the ground up may allow him to better sequence the delivery, improve force transfer, and create a more repeatable release pattern.",
    ],
    optimalSequence: "Pelvis Rotation → Torso Rotation → Elbow Extension → Shoulder Rotation",
    athleteSequence: "Torso Rotation → Pelvis Rotation → Elbow Extension → Shoulder Rotation",
  },
  kpiHeading: "Key Performance indicators",
  sections: [
    {
      id: "shoulder-horizontal-abduction",
      title: "Shoulder Horizontal Abduction",
      image: "/throwing/shoulder-horizontal-abduction.png",
      paragraphs: [
        "Shoulder horizontal abduction is a critical component of a thrower's arm action and describes the angle between the throwing arm and the upper trunk during the loading phase of the delivery. Allowing the arm to work slightly behind the trunk increases the available arc of motion, creating more time and space for force development and acceleration.",
        "Gavin demonstrates an optimal amount of shoulder horizontal abduction, or scapular loading, during the throwing motion. This position facilitates appropriate scapular retraction, allowing the posterior musculature of the rib cage to contribute to the stretch-shortening cycle generated through hip-to-shoulder separation. Effective scapular loading promotes engagement of the rhomboids, lower trapezius, and latissimus dorsi while creating an eccentric loading strategy of the serratus anterior and pectoralis major to help control scapular position and store elastic energy.",
        "Excessive horizontal abduction, however, can compromise scapular mechanics by increasing anterior tilt of the scapula. This may reduce the athlete's ability to achieve adequate posterior tilt and efficiently externally rotate the shoulder during the throwing motion, potentially limiting both force transfer and arm efficiency.",
      ],
    },
    {
      id: "shoulder-abduction",
      title: "Shoulder Abduction",
      image: "/throwing/shoulder-abduction.png",
      paragraphs: [
        "Shoulder abduction refers to the position of the upper arm relative to the trunk in the frontal plane and is a critical component of efficient throwing mechanics. In high-level throwers, shoulder abduction is typically maintained near 90 degrees, although individual variation exists. While shoulder abduction is often associated with arm slot, our motion capture analysis has consistently shown that elite throwers tend to maintain the upper arm in alignment with the acromion line and shoulder girdle throughout the throwing motion. Deviations from this relationship can alter kinematics and create compensatory movement patterns throughout the kinetic chain.",
        "Gavin demonstrates an optimal shoulder abduction position, allowing him to maintain favorable glenohumeral congruency and efficiently load the shoulder complex during the throwing motion. Proper shoulder abduction helps center the humeral head within the glenoid, providing a stable foundation for force transfer and rotational velocity.",
        "Limitations in shoulder abduction are often associated with an inability of the latissimus dorsi, pectoralis minor, and subscapularis to eccentrically orient and lengthen during the loading phase of the delivery. As a result, the arm may sit below the ideal position, compromising scapular and glenohumeral mechanics.",
        "At front foot strike, optimal shoulder abduction is typically observed when the throwing elbow is aligned with the clavicle and shoulder girdle. This position is essential for effectively loading and unloading the arm through acceleration, maximizing velocity and command while minimizing unnecessary stress on the shoulder and elbow.",
      ],
    },
    {
      id: "shoulder-external-rotation",
      title: "Shoulder External Rotation",
      image: "/throwing/shoulder-external-rotation.png",
      paragraphs: [
        "Shoulder external rotation is a critical component of the throwing motion and plays an important role during both the loading and acceleration phases of the delivery. At front foot strike, elite throwers typically demonstrate approximately 60 degrees of shoulder external rotation as they prepare to transfer energy up the kinetic chain. Gavin exhibits an optimal amount of shoulder external rotation at foot plant; however, his maximal external rotation reaches 154 degrees, which falls slightly below the 160+ degrees commonly observed in elite throwers.",
        "Limitations in external rotation can be the result of mobility restrictions, but they may also reflect inefficiencies in movement strategy leading into foot plant and layback. Often referred to as \"layback,\" shoulder external rotation creates the elastic loading necessary for the musculature surrounding the shoulder to contribute to the stretch-shortening cycle that accelerates the arm through the cocking and acceleration phases. Efficient layback is dependent upon proper scapular mechanics, including posterior tilt, upward rotation, and retraction of the scapula.",
        "Gavin demonstrates excellent coordination of shoulder abduction and horizontal abduction while externally rotating the shoulder, allowing him to maintain favorable glenohumeral alignment and efficiently generate rotational velocity. He also successfully positions the arm within the scapular plane at ball release. The scapular plane, which lies approximately 30 to 40 degrees anterior to the frontal plane, represents the most efficient position for force transfer and shoulder function during acceleration.",
        "Failure to reach the scapular plane can result in what is commonly referred to as \"arm drag,\" where the arm lags behind trunk rotation and places additional stress on the shoulder and elbow. Maintaining the arm within the scapular plane allows Gavin to effectively utilize the serratus anterior throughout acceleration. The serratus anterior plays a critical role as an upward rotator and posterior tilter of the scapula, helping maintain scapular positioning and providing a stable foundation for efficient arm action and force transfer throughout the throw.",
      ],
    },
    {
      id: "elbow-flexion-angle",
      title: "Elbow Flexion Angle",
      image: "/throwing/elbow-flexion-angle.png",
      paragraphs: [
        "Elbow flexion angle refers to the amount of bend present at the elbow throughout the throwing motion. This is an important characteristic of arm action because it influences how efficiently the arm is able to load, rotate, and accelerate through release. It is important to note that biomechanics reports measure elbow flexion from the lateral aspect of the joint, meaning an elbow flexion angle reported as 110 degrees is often visually perceived as approximately 90 degrees of bend.",
        "Gavin demonstrates appropriate elbow flexion during the loading phase of the delivery but is unable to fully maintain this position as the arm transitions into acceleration. Excessive loss of elbow flexion during this phase is commonly referred to as \"forearm flyout,\" where the forearm begins extending prematurely as the shoulder is still rotating.",
        "Maintaining elbow flexion while the shoulder externally rotates into layback is critical for both performance and arm health. This position allows the arm to remain connected to the rotational forces generated by the trunk and shoulder complex, promoting a more efficient transfer of energy through the kinetic chain. Premature elbow extension can alter timing, negatively affect release point consistency, and increase stress placed on the shoulder and elbow during acceleration.",
        "The ability to maintain elbow flexion throughout shoulder rotation helps create a more repeatable arm path, improves consistency at ball release, and may reduce unnecessary loading on the throwing arm.",
      ],
    },
    {
      id: "lateral-torso-tilt",
      title: "Lateral Torso Tilt",
      image: "/throwing/lateral-torso-tilt.png",
      paragraphs: [
        "Lateral trunk tilt, often referred to as contralateral tilt, is a key contributor to a thrower's arm action and arm slot. Throwers with a more over-the-top arm slot typically demonstrate greater contralateral tilt, leaning the torso toward the glove side, while throwers with a lower three-quarter slot generally maintain a more neutral trunk position. Together with shoulder abduction, lateral trunk tilt helps determine the angle at which the arm delivers the baseball.",
        "During the drive phase of the delivery, however, lateral trunk tilt provides insight into a thrower's ability to maintain alignment between the torso and pelvis. Excessive tilt during this phase may indicate an inability to stay stacked, creating inefficiencies in force transfer and balance throughout the delivery. Gavin demonstrates excellent frontal plane control by maintaining a stacked torso position at foot plant, allowing his trunk to remain centered over the pelvis as he transitions into rotation.",
        "Common examples of poor stacking include the trunk drifting excessively toward the lead side, positioning the torso in front of the lead knee or hip at landing, or remaining behind the rear hip as the front foot contacts the ground. These compensations can alter timing and reduce the efficiency of energy transfer through the kinetic chain.",
        "Maintaining a stacked position at foot plant places the internal obliques, external obliques, and transverse abdominis in an optimal position to facilitate hip-to-shoulder separation. This creates an efficient environment for force generation and transfer, allowing energy produced from the ground to be transmitted through the trunk and ultimately into the throwing arm at ball release.",
      ],
    },
    {
      id: "torso-rotation",
      title: "Torso Rotation",
      image: "/throwing/torso-rotation.png",
      paragraphs: [
        "Torso rotation is one of the most important contributors to throwing performance, influencing velocity, command, and the ability to efficiently transfer energy through the kinetic chain. The position of the torso at foot plant plays a significant role in establishing proper sequencing throughout the delivery. If a thrower rotates the torso too early and arrives at foot strike in an open position, it can reduce separation between the shoulders and pelvis, contribute to arm-side misses, increase stress on the throwing arm, and limit velocity potential.",
        "Conversely, landing excessively closed can create its own set of challenges. Throwers who remain too closed at foot plant often compensate by rotating the torso aggressively after landing in order to get both eyes aligned with the target. This can disrupt timing and negatively affect the sequence of movement leading into acceleration.",
        "Proper torso positioning relative to the pelvis is essential for creating and maintaining shoulder-hip separation. This separation allows rotational energy to be stored and transferred efficiently from the lower half through the trunk and ultimately into the throwing arm. Gavin demonstrates premature trunk rotation at foot plant, which likely contributes to his reduced shoulder-hip separation and may help explain his inability to fully achieve an optimal kinematic sequence throughout the delivery.",
      ],
    },
    {
      id: "pelvis-rotation",
      title: "Pelvis Rotation",
      image: "/throwing/pelvis-rotation.png",
      paragraphs: [
        "Pelvis rotation is a key performance indicator and serves as a foundational component of an efficient throwing delivery. The amount of pelvic rotation present at foot plant influences a thrower's ability to create separation, sequence rotational movements effectively, and transfer force through the kinetic chain. Elite throwers typically land with approximately 30–45 degrees of pelvic rotation, positioning the lower half to continue rotating while allowing the upper body to remain closed and create separation.",
        "Landing excessively open may indicate that pelvic rotation was initiated too early, reducing the ability to store rotational energy into foot plant. Conversely, insufficient pelvic rotation at landing may suggest that the pelvis was unable to rotate efficiently into foot strike, limiting the foundation necessary for effective separation and sequencing.",
        "Gavin demonstrates less pelvic rotation at landing than what is typically observed in elite throwers. This may contribute to his reduced shoulder-hip separation and help explain the sequencing inefficiencies observed throughout the delivery. Without sufficient pelvic rotation into foot plant, the athlete may have difficulty creating the rotational stretch required to efficiently transfer energy from the lower half into the trunk and throwing arm.",
        "Achieving adequate pelvic rotation at landing is also critical for establishing lead-leg closed-chain internal rotation. This position provides the foundation for an effective lead-leg block, allowing the front hip to accept force, stabilize the pelvis, and create a stable axis around which the trunk can rotate. Efficient lead-leg stability ultimately enhances force transfer, rotational velocity, and overall throwing efficiency.",
      ],
    },
    {
      id: "hip-shoulder-separation",
      title: "Hip/Shoulder Separation",
      image: "/throwing/hip-shoulder-separation.png",
      paragraphs: [
        "Hip to shoulder separation refers to the rotational difference between the pelvis and trunk during the throwing motion. While this metric is often viewed as a key performance indicator, our motion capture analysis has shown that there is a relatively wide range of separation values that can be effective across elite throwers. More important than the absolute amount of separation is the athlete's ability to maintain that separation into foot plant.",
        "Elite throwers are able to keep the torso relatively stable while the pelvis rotates underneath them during the drive phase of the delivery. This allows rotational energy to be stored and transferred efficiently through the kinetic chain as the throw progresses into acceleration. The ability to maintain separation into foot plant creates the foundation for effective sequencing and force transfer from the lower half through the trunk and ultimately into the throwing arm.",
        "Gavin demonstrates a sufficient degree of hip to shoulder separation; however, he creates this separation through premature trunk rotation during the drive phase rather than allowing the pelvis to rotate underneath a more stable torso. As a result, separation is established earlier in the delivery and begins to dissipate prior to foot plant.",
        "Maintaining separation later into the delivery allows elite throwers to maximize proximal-to-distal energy transfer and optimize the timing of rotational sequencing. Releasing separation too early can reduce the amount of stored rotational energy available during acceleration and may contribute to inefficiencies throughout the throwing motion.",
      ],
    },
    {
      id: "lead-knee-flexion-angle",
      title: "Lead Knee Flexion Angle",
      image: "/throwing/lead-knee-flexion-angle.png",
      paragraphs: [
        "Lead knee flexion angle refers to the amount of bend present in the front knee throughout the throwing motion. This metric provides insight into a thrower's ability to stabilize the lower half and efficiently transfer force through the lead leg during acceleration. High-level throwers are typically able to resist excessive knee flexion after front foot strike, creating a stable base that supports trunk rotation and force transfer into ball release.",
        "The ability to maintain lead leg stability during acceleration is a critical component of an effective lead-leg block. As rotational forces move up the kinetic chain, the lead leg serves as an anchor point that allows energy generated by the lower half to be redirected through the trunk and into the throwing arm. Excessive knee flexion during this phase can reduce stability and diminish the efficiency of force transfer.",
        "Gavin demonstrates a tendency to lose lead knee extension as he approaches ball release, limiting his ability to consistently maintain a firm lead leg block. This may reduce the stability available at release and contribute to variability in arm action and release point consistency. Improving the ability to resist lead knee flexion later into the delivery may help create a more stable rotational axis and enhance overall throwing efficiency.",
      ],
    },
    {
      id: "lead-knee-extension-angular-velocity",
      title: "Lead Knee Extension Angular Velocity",
      image: "/throwing/lead-knee-extension-angular-velocity.png",
      paragraphs: [
        "Lead knee extension angular velocity is an important indicator of a thrower's ability to transfer force from the ground through the kinetic chain and into the throwing arm. As the front foot accepts force, the lead leg must stabilize and extend to create a firm base for rotation. This action helps redirect ground reaction forces through the pelvis and trunk, contributing to efficient energy transfer during acceleration.",
        "Gavin demonstrates a relatively low degree of lead knee extension velocity, which may be influenced by his tendency to maintain increased knee flexion as he approaches ball release. Limited lead-leg extension can reduce the effectiveness of the lead-leg block and diminish the amount of force transferred through the lower half.",
        "Lead knee extension velocity is also closely related to an athlete's ability to eccentrically control the hamstrings while accepting and redirecting force through the front side. Gavin appears to rely more heavily on lead hip internal rotation to create this eccentric control as the pelvis continues rotating around the lead leg. However, this occurs primarily after ball release rather than during the critical acceleration phase of the delivery.",
        "This pattern can often be identified when the belt buckle continues rotating toward the lead hip after release. While this strategy may allow Gavin to utilize additional forward trunk rotation through eccentric hamstring control, improving the timing of lead-leg stabilization and extension may enhance force transfer earlier in the delivery and create a more efficient pathway for energy to reach the throwing arm.",
      ],
    },
    {
      id: "pelvis-rotation-angular-velocity",
      title: "Pelvis Rotation Angular Velocity",
      image: "/throwing/pelvis-rotation-angular-velocity.png",
      paragraphs: [
        "Pelvis rotation angular velocity refers to the speed at which the pelvis rotates toward home plate during the throwing motion. While peak pelvic rotational velocity is not necessarily a key performance indicator by itself, it provides valuable insight into a thrower's sequencing and ability to transfer energy through the kinetic chain. More important than the magnitude of pelvic rotation velocity is the timing of when it occurs relative to the trunk.",
        "In efficient throwers, peak pelvic rotational velocity typically occurs before peak torso rotational velocity. As the pelvis begins to decelerate, energy is transferred up the chain, allowing the trunk to accelerate and continue the sequencing process into the throwing arm. This relationship is often influenced by a thrower's positioning at foot plant, including pelvic rotation and the ability to create and maintain hip to shoulder separation.",
        "Gavin demonstrates a sequencing pattern in which peak pelvic rotational velocity does not occur sufficiently ahead of peak torso rotational velocity. This may be related to his limited pelvic rotation at landing and reduced hip-to-shoulder separation at foot plant. Without establishing these positions early in the delivery, the pelvis may be unable to effectively create and transfer rotational energy to the trunk.",
        "The ability to accelerate and subsequently decelerate the pelvis at the appropriate time is a critical component of the kinematic sequence. When this occurs efficiently, rotational energy is transferred proximally to distally, allowing the trunk, arm, and ball to accelerate more effectively throughout the delivery.",
      ],
    },
    {
      id: "torso-rotation-angular-velocity",
      title: "Torso Rotation Angular Velocity",
      image: "/throwing/torso-rotation-angular-velocity.png",
      paragraphs: [
        "Torso rotation angular velocity is a critical component of throwing performance and plays a major role in a thrower's ability to generate velocity, efficiently transfer energy, and consistently deliver the baseball. Within an efficient kinematic sequence, peak torso rotational velocity should occur after peak pelvic rotational velocity, allowing energy generated by the lower half to be transferred through the trunk and ultimately into the throwing arm.",
        "Gavin demonstrates an early onset of torso rotation, limiting his ability to fully capitalize on the rotational energy generated by the pelvis. This sequencing pattern may be influenced by his limited pelvic rotation at foot plant, which reduces the amount of separation and rotational energy available to be transferred up the kinetic chain.",
        "When pelvic rotation is insufficient at landing, throwers will often compensate by rotating the trunk earlier in an effort to square the torso to the target. While this strategy may help direct the ball toward home plate, it can disrupt the timing of the kinematic sequence and reduce the efficiency of force transfer throughout the delivery.",
        "The ability to delay torso rotation while allowing the pelvis to rotate and decelerate underneath the trunk is a hallmark of efficient throwers. This creates a more effective transfer of energy from the lower half into the upper body, allowing the trunk to reach higher rotational velocities at the appropriate time and improving both velocity potential and overall throwing efficiency.",
      ],
    },
    {
      id: "elbow-extension-velocity",
      title: "Elbow Extension Velocity",
      image: "/throwing/elbow-extension-velocity.png",
      paragraphs: [
        "Elbow extension velocity is an important indicator of how effectively a thrower transfers energy through the upper extremity during the acceleration phase of the throwing motion. While elbow extension itself does not generate velocity, the speed at which the elbow extends can provide insight into the efficiency of the kinematic sequence and how well energy is transferred from the lower half, through the trunk, and ultimately into the baseball.",
        "Efficient throwers are able to utilize rotational forces generated earlier in the delivery to create a whip-like effect through the arm, allowing energy to transfer from proximal segments to distal segments before being released through the fingertips at ball release. However, elevated elbow extension velocity can also indicate a greater reliance on the distal portions of the kinetic chain to generate ball velocity, particularly when force generation and sequencing earlier in the delivery are suboptimal.",
        "Despite displaying several inefficiencies in his proximal sequencing, Gavin demonstrates a relatively high degree of elbow extension velocity, even at lower levels of intent. This suggests he possesses the ability to create and transfer speed through the arm effectively, likely relying on the athleticism and rotational capacity of the upper extremity to compensate for limitations observed earlier in the kinematic sequence.",
        "Improving the timing and efficiency of force transfer through the pelvis and trunk may allow Gavin to further leverage his existing arm speed while reducing the amount of stress placed on the distal segments of the throwing arm to generate velocity.",
      ],
    },
    {
      id: "shoulder-internal-rotation-angular-velocity",
      title: "Shoulder Internal Rotation Angular Velocity",
      image: "/throwing/shoulder-internal-rotation-angular-velocity.png",
      paragraphs: [
        "Shoulder internal rotation angular velocity is one of the most important metrics in the throwing motion and is often considered the final expression of how efficiently a thrower transfers energy through the kinetic chain. The shoulder is capable of reaching extremely high rotational velocities during acceleration, making internal rotation one of the fastest movements observed in sport.",
        "This velocity is created as the shoulder transitions from maximal external rotation into rapid internal rotation during acceleration. During layback, the musculature responsible for internal rotation is placed under significant stretch and eccentric load before rapidly transitioning to a concentric contraction to accelerate the arm and propel the baseball toward the target. Many elite throwers describe this sensation as \"getting on top of the ball\" or \"pulling down through the baseball\" as they move through release.",
        "Because shoulder internal rotation angular velocity occurs at the end of the kinematic sequence, it is highly dependent on the efficient transfer of energy from the ground through the pelvis, trunk, scapula, and upper extremity. As a result, this metric often reflects not only the rotational capacity of the shoulder itself, but also the effectiveness of the movements that precede it.",
        "Gavin demonstrates a lower degree of shoulder internal rotation angular velocity than what is typically observed in elite throwers. This may be influenced by the sequencing inefficiencies identified earlier in the delivery, limiting the amount of rotational energy available to be transferred into the arm. Additionally, shoulder internal rotation velocity can be influenced by an athlete's ability to dynamically position and move the scapula on the rib cage throughout the throwing motion. Efficient scapular movement provides the foundation for optimal shoulder function and allows rotational forces generated by the lower half and trunk to be fully expressed through the throwing arm.",
        "Improving the efficiency of force transfer earlier in the delivery may allow Gavin to better utilize the rotational capacity of the shoulder and increase the amount of internal rotation velocity available at ball release.",
      ],
    },
  ] satisfies ThrowingPdfSection[],
  suggestions: {
    title: "Suggestions",
    paragraphs: [
      "Gavin demonstrates many of the foundational movement characteristics commonly observed in high-level throwers. However, he was unable to consistently achieve an efficient kinematic sequence, which refers to the ability to transfer energy from proximal segments to distal segments throughout the delivery. Efficient sequencing requires the pelvis to initiate rotation, followed by the trunk, arm, and ultimately the baseball.",
      "One factor contributing to this pattern appears to be Gavin's limited degree of pelvic rotation at foot plant. Pelvic positioning at landing is often reflective of how a thrower organized movement throughout the drive phase and can significantly influence the timing of subsequent rotational events. In Gavin's case, he creates separation by rotating the trunk over a relatively fixed pelvis rather than allowing the pelvis to rotate underneath a stable torso. While this strategy allows him to create measurable hip-to-shoulder separation, it may contribute to the premature trunk rotation observed later in the delivery.",
      "As a result, Gavin appears to rely on compensatory movement strategies, including early trunk rotation and premature elbow extension, to align the upper body with the intended target. These patterns can reduce the efficiency of force transfer throughout the kinetic chain and may contribute to variability in release point consistency.",
      "To improve sequencing, Gavin would likely benefit from activities that enhance dynamic control of closed-chain hip mechanics and improve his ability to rotate the pelvis independently of the trunk. Developing greater control of pelvic rotation may improve his ability to create and maintain separation later into the delivery while optimizing the transfer of energy from the lower half into the throwing arm.",
      "Additionally, drills that emphasize pelvis-to-torso dissociation and rotational timing may help improve both the magnitude and timing of hip-to-shoulder separation. Improving these movement qualities could allow Gavin to sequence more efficiently, maximize force transfer through the kinetic chain, and create a more repeatable release point throughout the delivery.",
    ],
  },
};
